version: '3.7'

services:
    web:
        build: .
        command: python /app/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db
        networks:
            - internal-network


    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: hunter2
        networks:
            - internal-network

networks:
  internal-network:

volumes:
  postgres_data:
